spring.application.name=gym-hub
spring.datasource.url=jdbc:mysql://localhost:3306/gym_hub?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true

# Usuário e senha do seu MySQL
spring.datasource.username=root
spring.datasource.password=mysqlPW
server.port=8081
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect