spring.application.name=gym-hub
server.port=8081

# CORREÇÃO AQUI: Removida a repetição de "spring.datasource.url="
spring.datasource.url=jdbc:mysql://localhost:3306/gym_hub?allowPublicKeyRetrieval=true&useSSL=false

# Usuário e senha do seu MySQL
spring.datasource.username=root
spring.datasource.password=mysqlPW

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Opcional: Removido o dialect manual pois o Hibernate 6+ já detecta automaticamente